import type { TableState } from '../types/game';

// 假数据：6 人桌，turn 阶段（已翻 4 张公共牌），轮到 seat=2 行动
export function buildMockTable(): TableState {
  const now = Date.now();
  return {
    roomId: '1234',
    maxSeats: 6,
    smallBlind: 100,
    bigBlind: 200,
    pot: 1200,
    currentBet: 200,
    minRaise: 200,
    stage: 'turn',
    activeSeat: 2,
    actionDeadline: now + 30_000,
    revealedCount: 4,
    communityCards: [
      { suit: 'heart', rank: 'A' },
      { suit: 'spade', rank: '10' },
      { suit: 'diamond', rank: 'K' },
      { suit: 'club', rank: '7' },
      { suit: 'heart', rank: '2' },
    ],
    players: [
      {
        seat: 0,
        uid: 'me',
        nickname: '我',
        avatar: '😎',
        chips: 3800,
        betThisRound: 200,
        status: 'acted',
        holeCards: [
          { suit: 'spade', rank: 'A' },
          { suit: 'heart', rank: 'K' },
        ],
        isMe: true,
        isDealer: false,
        isSmallBlind: false,
        isBigBlind: true,
      },
      {
        seat: 1,
        uid: 'p1',
        nickname: '小明',
        avatar: '🐱',
        chips: 4500,
        betThisRound: 200,
        status: 'acted',
        holeCards: [],
        isMe: false,
        isDealer: false,
        isSmallBlind: false,
        isBigBlind: false,
      },
      {
        seat: 2,
        uid: 'p2',
        nickname: '阿强',
        avatar: '🦁',
        chips: 2100,
        betThisRound: 0,
        status: 'thinking',
        holeCards: [],
        isMe: false,
        isDealer: true,
        isSmallBlind: false,
        isBigBlind: false,
      },
      {
        seat: 3,
        uid: 'p3',
        nickname: 'Cici',
        avatar: '🐰',
        chips: 0,
        betThisRound: 800,
        status: 'all-in',
        holeCards: [],
        isMe: false,
        isDealer: false,
        isSmallBlind: false,
        isBigBlind: false,
      },
      {
        seat: 4,
        uid: 'p4',
        nickname: '老李',
        avatar: '🐼',
        chips: 5600,
        betThisRound: 0,
        status: 'folded',
        holeCards: [],
        isMe: false,
        isDealer: false,
        isSmallBlind: false,
        isBigBlind: false,
      },
      {
        seat: 5,
        uid: 'p5',
        nickname: 'Mia',
        avatar: '🦊',
        chips: 3200,
        betThisRound: 100,
        status: 'acted',
        holeCards: [],
        isMe: false,
        isDealer: false,
        isSmallBlind: true,
        isBigBlind: false,
      },
    ],
  };
}
